Qa/ui2
wafflestudio/SNUTT-web pull request #57
Opened 2022-02-02 12:38 UTC by mike0295

- 메인뷰 교양 강의평 변경된 API 반영
- Create뷰 툴팁 구현 (반만 완성, MUI 썼는데 색깔과 패딩 어떻게 수정하는지 못 찾음)
- 강의평 태그 검색 시 태그 추가 버튼 아래로 내려가서 터치 안되는 버그 수정
- 디테일 뷰 강의평 없을 시 고양이 띄우기 구현
- 메인뷰 최근 강의평 아이콘 수정

추가
- 메인뷰 태그 리뷰 클릭되는 컴포넌트 변경
- 리뷰 글귀 텍스트 화면 밖으로 넘어가는 버그 수정
- 메인뷰 태그 강의평 목록에 강의평 없을때 고양이 추가
- 엔터 쳐서 검색
- 검색뷰에 검색결과 없음 페이지 추가
- 검색뷰 처음에 도우미 글 뜨게 변경 (TODO: 인풋 비었을떄 아예 API 호출 안하게 수정 필요)

2022-02-02 14:35 UTC, JSKeum requested changes

2022-02-02 14:35 UTC, JSKeum commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +            disableHoverListener
hover할 때 disable 되는 게 맞나요?

2022-02-02 14:35 UTC, JSKeum commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +const TooltipButton = styled.div``
Button은 시맨틱하게 `button`으로 구현해주세요. onClick을 사용한다 -> 99% button 태그. 시맨틱뿐 아니라 때로는 기능 상에서도 문제가 발생할 수 있어요

2022-02-02 14:35 UTC, JSKeum commented on pageImpl/createImpl/__components__/ToolTipContent.tsx
> +import React from "react"
react는 import하지 않아도 될거예요

2022-02-02 14:35 UTC, JSKeum commented on pageImpl/detailImpl/index.tsx
> +  const isEmpty = count === 0 && myReviewResult?.evaluations.length === 0
`count`와 `myReviewResult` 둘다 옵셔널인데, 이 친구들이 null 또는 undefined 일 때(로딩 중일 때)도 의도한 대로 동작하나요??

2022-02-02 15:08 UTC, mike0295 commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +            disableHoverListener
넵 어차피 모바일에선 hover라는 개념이 없으니까요 (아마도)
disableTouchListener가 걱정이라면 그건 꾹 누르는걸 뜻하고, 터치는 disableInteractive라는 prop이 따로 있습니다

2022-02-02 15:19 UTC, mike0295 commented on pageImpl/detailImpl/index.tsx
> +  const isEmpty = count === 0 && myReviewResult?.evaluations.length === 0
흠 다시보니 로딩중일때 한번 깜빡 하네요... undefined면 아예 백지를 띄워야 할까요?

2022-02-02 15:19 UTC, mike0295 commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +const TooltipButton = styled.div``
반영완료

2022-02-02 15:19 UTC, mike0295 commented on pageImpl/createImpl/__components__/ToolTipContent.tsx
> +import React from "react"
반영완료

2022-02-04 12:16 UTC, JSKeum commented on pageImpl/detailImpl/index.tsx
> +  const isEmpty = count === 0 && myReviewResult?.evaluations.length === 0
아예 백지를 띄우던지, 로딩 아이콘을 띄우던지 해야할듯

2022-02-05 06:52 UTC, mike0295 commented on pageImpl/detailImpl/index.tsx
> +  const isEmpty = count === 0 && myReviewResult?.evaluations.length === 0
반영완료

2022-02-05 07:16 UTC, merged

2022-02-05 07:55 UTC, ars-ki-00 commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +
구경하다가 진짜진짜 궁금한 점
이거 잘 적용돼요,,,?

2022-02-05 08:50 UTC, ars-ki-00 commented on pageImpl/createImpl/__components__/EvalPolygon.tsx
> +
@mike0295 
unstable한 해시값이네 참고
https://mui.com/customization/how-to-customize/#overriding-nested-component-styles